Добавляет разметку header
wrgraff/2366847-device-36 pull request #2
Opened 2023-05-03 19:24 UTC by KseniaT3

2023-05-04 16:18 UTC, wrgraff requested changes
[Посмотри правила](https://telegra.ph/Pravila-revyu-04-02), по которым я в целом делаю ревью, чтобы лучше ориентироваться.

Если что-то непонятно — пиши =)

2023-05-04 16:18 UTC, wrgraff commented on index.html
> +            </svg>
Сейчас наша задача — сделать именно семантическую разметку. Поэтому, мы должны пока что вставить _контентные_ изображения. Иконки — изображения декоративные, и их сейчас вставлять не нужно.

Тем более, нужно сперва разобраться: когда их делать через фон, когда через псевдоэлемент, когда через <img> и когда <svg>. Все это разные случаи.
А то у тебя тут уже заготовка под спрайт, а мы его по идее на этом курсе не проходим даже (но можем рассмотреть, если успеем)

2023-05-04 16:18 UTC, wrgraff commented on index.html
> +            </a>
Лучше не оставлять контент в конце открывающего тега, потому что его так будет хуже видно при просмотре кода.
Когда взгляд бросаешь, то ориентируешься по началу строки, а в конец не особо смотришь.

Тут конечно иконку наверное нам и не нужно помещать будет, но можно было бы как-то так оформить

```html
<a class="navigation-link" href="#">
  Войти
  <svg  aria-hidden="true">
    <use class="navigation-icon" href="#"></use>
  </svg>
</a>
```

А вот если содержимого почти нет, то логично оставить так:
```html
<a class="navigation-link" href="#">Войти</a>
```

Но иногда делают так, тут кому как удобнее:
```html
<a class="navigation-link" href="#">
  Войти
</a>
```

2023-05-04 16:18 UTC, wrgraff commented on index.html
> +            </a>
Это же часть формы поиска, а не ссылка

2023-05-06 16:07 UTC, KseniaT3 commented on index.html
> +      <nav class="main-navigation">
1. VS code
2. да, плагин ставила

2023-05-09 12:59 UTC, wrgraff requested changes
Многое получилось исправить, но часть пока еще требует доработок

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +          <form action=""https://echo.htmlacademy.ru" method="POST">
Тут вышла путаница с кавычками.
Это должно быть хорошо заметно по подсветке синтаксиса в VS Code

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +        <h2 class="visually-hiden">Адрес</h2><!--после разметки main уже будет другой h-->
Почему будет другой?

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +        <h2 class="visually-hiden">Контакты</h2><!--после разметки main уже будет другой h-->
Почему другой? Как другой раздел повлияет на заголовки в футере?

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +        </div>
Сейчас нам важны только семантические элементы.
Более того, такие пустые чисто визуальные элементы не должны быть в разметке в виде тега, для их реализации используются стили

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +      <nav class="footer-navigation">
А где закрывающая часть этого тега?

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +      <section>
Какой-то непонятный `<section>`: заголовка у него нет, а объединяет он навигацию и соцсети. Точно ли их нужно объединить?

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +             <span class="visually-hiden">Ютьюб</span>
Чтобы подписать ссылку скрытым текстом, текст должен быть внутри нее

2023-05-09 12:59 UTC, wrgraff commented on index.html
> +    <section>
Пока что нужно сосредоточиться на семантике.
Если где-то для оформления нужен будет `<div>` — без проблем добавишь. Так как семантически дивы ценности не имеют, можно пока обойтись без них, делая минимум необходимой семантики

2023-05-16 18:26 UTC, wrgraff requested changes

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +        </ol>
Надо еще 2 пункта разметить )

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +                мощным лазером, замаскированным под стандартную камеру.</p>
Ну, немного странное название )

Непонятно откуда `pagination`.
Не очень понятно почему часть классов с `item`, а часть без.

Я бы сделал `slider-item-title` или `slider-title`.
Чтобы не было два `description`, один (который внутри) можно назвать `text`, например

2023-05-16 18:26 UTC, wrgraff commented on index.html
>            </li>
Нужно наполнить контентом обязательно их

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +        <p class="">Огромный выбор гаджетов не оставит равнодушным
А чего он пустой )
Раз есть класс, то уж надо туда что-нибудь закинуть!
Если что, подглядывай в [шпаргалку с часто используемыми словами](https://github.com/yoksel/common-words)

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +        <button class="button about-button">Подробнее о нас</button>
Это 99.9% — ссылка, оформленная в виде кнопки.
Ведет на страницу "О нас". Вряд ли она делает что-то эдакое интерактивное на странице

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +        <button class="button contacts-button">Напишите нам</button>
Тоже кнопка аналогично. На вид кнопка, по факту ссылка

2023-05-16 18:26 UTC, wrgraff commented on index.html
> +      <section class="signup">
Лучше `subscribe`. Sign up это регистрация

2023-05-23 17:23 UTC, wrgraff requested changes

2023-05-23 17:23 UTC, wrgraff commented on index.html
>          </ul>
В этом списке 3 пункта с заголовками, во всех заголовках потерялась буква в слове "class" =)

https://github.com/wrgraff/2366847-device-36/blob/b40d03a082a4e398a535bf582f0779b3b18b7836/index.html#L181
https://github.com/wrgraff/2366847-device-36/blob/b40d03a082a4e398a535bf582f0779b3b18b7836/index.html#L187
https://github.com/wrgraff/2366847-device-36/blob/b40d03a082a4e398a535bf582f0779b3b18b7836/index.html#L193

2023-05-23 17:23 UTC, wrgraff commented on index.html
> +              <a class="button" href="#">подробнее</a>
Вообще, все тексты принято писать как обычные. Если отдельно взятое слово, то с большой буквы:
`<a class="button" href="#">Подробнее</a>`

2023-05-23 17:23 UTC, wrgraff commented on index.html
> +              <table class="slider-pagination-item-characteristics">
Здесь наверное тоже `pagination` лишний в имени класса

2023-05-30 19:45 UTC, wrgraff approved these changes
Вышло весьма неплохо, есть небольшая путаница с разделением на блоки между фильтром и сортировкой. И нужно чуть разобраться с заголовками

2023-05-30 19:45 UTC, wrgraff commented on index.html
> +      <section class="signup">
Мы же меняли `signup` на `subscribe`, потому что `signup` — это регистрация.
Надо было `signup-description` сменить на `subscribe-description`, а не возвращать `signup` =)

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +      <h1 class="visually-hidden">Каталог</h1>
У нас же есть отличный кандидат на основной заголовок: "Моноподы для селфи".
Эта страница ведь именно про них. А заголовок "Каталог" мог бы быть у общей страницы каталога

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +            <a class="catalog-breadcrumb-link" href="#">Главная</a>
У нас же есть адрес главной страницы

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +            <a class="catalog-breadcrumb-link" href="#">Моноподы для селфи</a>
А это — текущая страница. Нужно или поставить адрес этой страницы, или убрать `href` (тут есть 2 подхода: мы или ставим ссылку страницы на саму себя или нет. Судя по главной — ставим)

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +        <h2>ФИЛЬТР:</h2>
Все заглавные делаются через стили, здесь же нужно писать по простому:
```suggestion
        <h2>Фильтр:</h2>
```

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +        </div>
Слайдер верстать мы пока что не умеем, это будет позже по программе, как и формы в целом.
Пока что можно поставить тут коммент или вовсе пустоту оставить

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +          <ul>
Тут немного в кучу всё получилось.
У нас можно логически поделить эти блоки на 3 секции:
- фильтр
- сортировка
- список товаров

<img width="723" alt="изображение" src="https://github.com/wrgraff/2366847-device-36/assets/37917037/020893c9-aaba-40af-99c6-0a503a6e6334">

Сейчас мы должны думать о семантике, потом уже о том как их сверстать.
По порядку сверху вниз и слева направо, как по списку выше должно получиться.

У каждого `<section>` крайне желательно ставить свой заголовок.
То есть, если у нас есть несколько `<section>` внутри `<main>` после заголовка 1-го уровня, то внутри каждого должен быть основной заголовок 2-го уровня:

```html
<h1>
<section>
  <h2>
  ...
  <h3>
  ...
</section>

<section>
  <h2>
  ...
  <h3>
  ...
  <h3>
  ...
</section>
```

В одном из них могут быть еще секции (да, внутри одних могут быть и другие — а кто нам запретит, если логика содержимого позволяет?). Тогда там старшим будет следующий заголовок


```html
<h1>
<section>
  <h2>
  ...
  <h3>
  ...
</section>

<section>
  <h2>
  ...
  <section>
    <h3>
    ...
    <h4>
    ...
  </section>
  <section>
    <h3>
    ...
    <h4>
    ...
    <h4>
    ...
  </section>
</section>
```

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +        <button class="button" type="button">Показать</button>
Эта кнопка должна отправить нашу форму, поэтому у нее должен быть другой тип как раз:
```suggestion
        <button class="button" type="submit">Показать</button>
```

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +      <section>
Тут хорошо, что выделила секшн, но еще ему надо бы заголовок.
Логика секшенов в том, что это какой-то законченный осмысленный блок контента. А раз он осмысленный — можно его как-то назвать

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +            <a class="product-card-link" href="product.html">
А вот страницы продукта у нас как раз нет )
Раз уж мы ставим несуществующим адресам решетки, то и тут надо поставить решетку
```suggestion
            <a class="product-card-link" href="#">
```

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +              <h3 class="product-card-title">Профессиональная селфи-палка</h3>
Сейчас по идее это заголовки второго уровня должны быть, что не очень то уместно.
А когда озаглавишь список товаров — будет как раз подходить третий уровень

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +        <h3 class="visually-hidden">Страницы</h3>
Тут непонятно почему третий уровень.
Раз идет после другого секшена — должен быть как и в предыдущем второй.

Но на самом деле я бы вообще пагинацию не отделял, а поместил в секшн со списком товаров. Она ведь относится именно к списку, поэтому логично их объединить в один целый логический блок

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +              <span class="visually-hidden">НАЗАД</span>
Везде, по всему макету пишем обычным текстом

```suggestion
              <span class="visually-hidden">Назад</span>
```

2023-05-30 19:45 UTC, wrgraff commented on catalog.html
> +            <a class="pagination-link pagination-current">1</a>
Нужно определиться, есть у нас ссылки у страниц на самих себя или нет

2023-05-31 06:55 UTC, wrgraff requested changes

2023-05-31 06:55 UTC, wrgraff commented on catalog.html
> +            <a class="catalog-breadcrumb-link" href="catalog.html">Каталог товаров</a>
Смотри, текущая страница — это не "каталог товаров", это подраздел каталога "моноподы для селфи" внутри каталога товаров.
Соответственно, тут ссылка стоит не там

2023-05-31 06:55 UTC, wrgraff commented on catalog.html
> +      <h1 class="visually-hidden">Каталог</h1>
Непонятно почему заголовок переехал вверх.
Основной заголовок этой страницы — "Моноподы для селфи", потому что это именно эта страница в каталоге товаров.
Заголовок "Каталог товаров" мог бы быть на основной странице каталога. На другой странице то есть, не на этой

2023-05-31 06:55 UTC, wrgraff commented on catalog.html
> +        <button class="catalog-drop-button">Популярное</button>
Кнопкам обязательно нужно прописать атрибут `type`.

По умолчанию кнопки работают как отправка формы. И если случайно из-за глюка в коде с незакрытым тегом формы наша кнопка отправит данные вместо переключения слайдера, то будет не здорово 🙃

Поэтому, таким кнопкам обязательно надо прописать `type="button"`.

Есть и еще момент. Надо прописывать и `type="submit"` тоже. Зачем прописывать значение по умолчанию?

А все просто: ради декларативности. То есть, если я посмотрю на кнопку, я *точно* буду знать какого она типа, если в ней этот тип написан. А если не написан, то буду сидеть и сомневаться: "это я забыл прописать или значение по умолчанию хотел использовать?".

2023-05-31 06:55 UTC, wrgraff commented on catalog.html
> +        <a class="catalog-button" href="#"><span class="visually-hidden">Вниз</span></a>
Лучше конечно написать текст "По убыванию" и "По возрастанию", а то не очень понятно что такое вниз и вверх

2023-05-31 07:16 UTC, wrgraff approved these changes

2023-05-31 07:16 UTC, merged